### ISSUE TITLE
Test fails thus no installation

### ISSUE THREAD

**Issue by wbiker** [labster/p6-file-directory-tree#14]
Hi, first of all, thanks for the module.

Unfortunately, I cannot install it, because a test fails:
% zef install File::Directory::Tree
===> Searching for: File::Directory::Tree
===> Testing: File::Directory::Tree:auth('labster')
No such method 'child' for invocant of type 'Bool'
  in block  at t/basic.t line 32
  in block <unit> at t/basic.t line 30

# Looks like you planned 9 tests, but ran 7
===> Testing [FAIL]: File::Directory::Tree:auth('labster')

**Comment by szabgab** [comment]
Which version of Rakudo and what operating system?

**Comment by wbiker** [comment]
Ups. Sorry. Old rakudo version. 2016. I updated to the most recent one and installation works just fine. Sorry for the noise.

**Comment by szabgab** [comment]
No problem at all.
