### ISSUE TITLE
Tests are failing now

### ISSUE THREAD

**Issue by JJ** [labster/p6-file-directory-tree#15]
Travis tests are failing.

**Comment by Scimon** [comment]
Forked and running the tests locally (with 2019.07) they are fine. The travis tests seem to be running with 2018.05. 

Can you give me a pointer to your test Docker Images and I'll look to see about implementing them?

**Comment by Scimon** [comment]
Branched the repo and ran the tests in Travis and it built fine.

https://travis-ci.org/Scimon/p6-file-directory-tree (The failed test here was run a year ago).

**Comment by JJ** [comment]
OK, thanks for testing. I close it then.

**Comment by JJ** [comment]
I'm going to install new tests, just in case.
